// Regenerate psl-data.js from the upstream Public Suffix List.
//
//   node scripts/gen-psl.mjs
//
// Fetches publicsuffix.org's list, keeps only the ICANN section (the registry
// suffixes — not the PRIVATE section, so allowing a domain still covers the
// services hosted under it), and writes the rules as two newline-joined strings
// that psl-data.js turns into Sets at load. Run it when you want to refresh the
// list; the generated file is committed so the build needs no network.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import punycode from "node:punycode";

const SRC = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "psl-data.js");

const text = await (await fetch(SRC)).text();

const rules = [];
const exceptions = [];
let inIcann = false;
for (const raw of text.split("\n")) {
  const line = raw.trim();
  if (line === "// ===BEGIN ICANN DOMAINS===") {
    inIcann = true;
    continue;
  }
  if (line === "// ===END ICANN DOMAINS===") break;
  if (!inIcann || !line || line.startsWith("//")) continue;
  // Store rules in ASCII (A-label / punycode) form so they match the punycode
  // hostnames the browser's URL parser produces for IDNs. ASCII rules pass
  // through unchanged; "*" and other punctuation are preserved.
  if (line.startsWith("!")) exceptions.push(punycode.toASCII(line.slice(1)));
  else rules.push(punycode.toASCII(line));
}

const banner = "// AUTO-GENERATED by scripts/gen-psl.mjs from the Public Suffix List (ICANN\n// section). Do not edit by hand — rerun the script to refresh.\n";
const body =
  `const RULES = ${JSON.stringify(rules.join("\n"))};\n` +
  `const EXCEPTIONS = ${JSON.stringify(exceptions.join("\n"))};\n` +
  "export const PSL_RULES = new Set(RULES.split('\\n'));\n" +
  "export const PSL_EXCEPTIONS = new Set(EXCEPTIONS.split('\\n'));\n";

writeFileSync(OUT, banner + body);
console.log(`psl-data.js: ${rules.length} rules, ${exceptions.length} exceptions`);
