// Regenerate palette.js from the installed Tailwind's default color theme.
// Parses node_modules/tailwindcss/theme.css (--color-*: oklch(...) / #hex),
// converts each to sRGB hex + precomputed OKLab, and writes ../palette.js used
// by lib.nearestTailwind. Run from the picker dir:  npm run gen:palette
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TW = join(ROOT, "node_modules", "tailwindcss");
const css = readFileSync(join(TW, "theme.css"), "utf8");
const version = JSON.parse(readFileSync(join(TW, "package.json"), "utf8")).version;

const clamp01 = (x) => Math.min(1, Math.max(0, x));
const toSrgb = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
const toLinear = (c) => {
  c /= 255;
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
};

// OKLCH (L 0..1, C, H deg) -> sRGB {r,g,b} 0..255 (gamut-clamped).
function oklchToRgb(L, C, H) {
  const h = (H * Math.PI) / 180;
  const a = C * Math.cos(h);
  const b = C * Math.sin(h);
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3;
  const m = m_ ** 3;
  const s = s_ ** 3;
  const R = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  const G = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  const B = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
  return {
    r: Math.round(clamp01(toSrgb(R)) * 255),
    g: Math.round(clamp01(toSrgb(G)) * 255),
    b: Math.round(clamp01(toSrgb(B)) * 255),
  };
}

// sRGB {r,g,b} -> OKLab (mirrors lib.rgbToOklab; kept here so the script is standalone).
function rgbToOklab({ r, g, b }) {
  const R = toLinear(r);
  const G = toLinear(g);
  const B = toLinear(b);
  const l = 0.4122214708 * R + 0.5363325363 * G + 0.0514459929 * B;
  const m = 0.2119034982 * R + 0.6806995451 * G + 0.1073969566 * B;
  const s = 0.0883024619 * R + 0.2817188376 * G + 0.6299787005 * B;
  const l_ = Math.cbrt(l);
  const m_ = Math.cbrt(m);
  const s_ = Math.cbrt(s);
  return {
    L: 0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_,
    a: 1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_,
    b: 0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_,
  };
}

const hex = ({ r, g, b }) => "#" + [r, g, b].map((n) => n.toString(16).padStart(2, "0")).join("");
const rd = (n) => Math.round(n * 100000) / 100000;

const seen = new Set();
const out = [];
const re = /--color-([a-z]+(?:-\d+)?):\s*(oklch\(([^)]+)\)|#[0-9a-fA-F]{3,8})\s*;/g;
let mm;
while ((mm = re.exec(css))) {
  const name = mm[1];
  if (seen.has(name)) continue;
  seen.add(name);
  let rgb;
  if (mm[2].startsWith("oklch")) {
    const p = mm[3].trim().split(/\s+/);
    const L = parseFloat(p[0]) / (p[0].includes("%") ? 100 : 1);
    rgb = oklchToRgb(L, parseFloat(p[1]), p[2] !== undefined ? parseFloat(p[2]) : 0);
  } else {
    let h = mm[2].slice(1);
    if (h.length === 3) h = h.split("").map((c) => c + c).join("");
    rgb = { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16) };
  }
  const ok = rgbToOklab(rgb);
  out.push({ name, hex: hex(rgb), L: rd(ok.L), a: rd(ok.a), b: rd(ok.b) });
}

const body = `// GENERATED by scripts/gen-palette.mjs from Tailwind v${version} (node_modules/tailwindcss/theme.css).
// Each entry: Tailwind color name, its sRGB hex, and precomputed OKLab (L,a,b)
// for nearest-color matching (lib.nearestTailwind). Re-run: npm run gen:palette
export const TAILWIND_VERSION = ${JSON.stringify(version)};
export const TAILWIND_COLORS = [
${out.map((c) => "  " + JSON.stringify(c)).join(",\n")},
];
`;
writeFileSync(join(ROOT, "palette.js"), body);
console.log(`wrote palette.js: ${out.length} colors (Tailwind v${version})`);
